#!/bin/sh
node auction -5 -R "griffen pet"

while true; do
    clear
    node auction -5 -R "griffin pet"
    echo
    echo "Sleeping 30..."
    sleep 10
    echo "Sleeping 20..."
    sleep 10
    echo "Sleeping 10..."
    sleep 10
done
