#!/bin/sh

export ARMOR="$1"
export OPTIONS="$2"

echo HELM
node auction $OPTIONS -o10 -X "growth protection thorns" -- "$ARMOR helm"
echo
echo CHEST PLATE
node auction $OPTIONS -o10 -X "growth protection thorns" -- "$ARMOR chestplate"
echo
echo LEGGINGS
node auction $OPTIONS -o10 -X "growth protection thorns" -- "$ARMOR leggings"
echo
echo BOOTS
node auction $OPTIONS -o10 -X "growth protection thorns" -- "$ARMOR boots"

node auction $OPTIONS -o1 -K -X "growth protection thorns" -- "$ARMOR helm" > .armor
node auction $OPTIONS -o1 -K -X "growth protection thorns" -- "$ARMOR chestplate" >> .armor
node auction $OPTIONS -o1 -K -X "growth protection thorns" -- "$ARMOR leggings" >> .armor
node auction $OPTIONS -o1 -K -X "growth protection thorns" -- "$ARMOR boots" >> .armor
echo
cat .armor | cut -c16-21 | sed 's/K//'g | awk '{ total += $1 } END { printf("Total: $%5.0fK\n", total) }'
rm .armor
