#!/bin/sh

export ARMOR=$1

echo HELM
node auction "$ARMOR helm" -x       | grep growth | grep protection | grep thorns | grep respiration | head -5
echo
echo CHEST PLATE
node auction "$ARMOR chestplate" -x | grep growth | grep protection | grep thorns | head -5
echo
echo LEGGINGS
node auction "$ARMOR leggings" -x   | grep growth | grep protection | grep thorns | head -5
echo
echo BOOTS
node auction "$ARMOR boots" -x      | grep protection | grep growth | grep thorns | grep feather | head -5


node auction -k "$ARMOR helm" -x | grep growth | grep protection | grep thorns | grep respiration | head -1 > .armor
node auction -k "$ARMOR chestplate" -x | grep growth | grep protection | grep thorns | head -1 >> .armor
node auction -k "$ARMOR leggings" -x | grep growth | grep protection | grep thorns | head -1 >> .armor
node auction -k "$ARMOR boots" -x | grep feather | grep protection | grep thorns | grep growth | head -1 >> .armor
echo
cat .armor | cut -c16-21 | sed 's/K//'g | awk '{ total += $1 } END { printf("Total: $%5.0fK\n", total) }'
rm .armor
