#!/bin/sh
node auc -e -l1 ender-slayer-6
# node auc -e -l1 experience-4
node auc -e -l1 fire-aspect-2
node auc -e -l1 giant-killer-6
node auc -e -l1 lethality-6
# node auc -e -l1 life-steal-4

# node auc -e -l1 looting-4
# node auc -e -l1 scavenger-4
node auc -e -l1 sharpness-6
# node auc -e -l1 thunderlord-6
node auc -e -l1 vamparism-6


# node auc -e -l1 cleave-5
# node auc -e -l1 critical-6
# node auc -e -l1 cubism-5
# node auc -e -l1 ender-slayer-6
# node auc -e -l1 execute-5
# node auc -e -l1 experience-4

# node auc -e -l1 fire-aspect-2
# node auc -e -l1 first-strike-4
# node auc -e -l1 giant-killer-6
# node auc -e -l1 impaling-3
# node auc -e -l1 lethality-6
# node auc -e -l1 life-steal-4

# node auc -e -l1 looting-4
# node auc -e -l1 luck-6
# node auc -e -l1 scavenger-4
# node auc -e -l1 sharpness-6
# node auc -e -l1 thunderlord-6
node auc -e -l1 vamparism-6

# node auc -e -l1 venemous-6
