#!/bin/sh
PETS="sheep guardian griffin"

while true; do
    clear
    node auction -a -p -t lege "wither skeleton"
    echo
    node auction -a -p -t lege "griffin"
    echo
    node auction -p -t lege -o5 "griffin"
    sleep 30
done
