#!/bin/sh
PETS="bat mithril-golem blue-whale dolphin monkey griffin "

while true; do
    clear
    for PET in $PETS; do
        PET=`echo $PET | sed s/-/\ /g`
        pet "$PET"
        echo
    done
    sleep 30
done
