#!/bin/sh
PETS="bat griffin blue-whale mithril-golem monkey dolphin"

while true; do
    clear
    for PET in $PETS; do
        PET=`echo $PET | sed s/-/\ /g`
        pet "$PET"
        echo
    done
    sleep 30
done
